site_name: MCG模组教程
theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
repo_url: https://github.com/MineCraftGensoukyo/ModdingTutorial

nav:
  - 前言: index.md
  - 巧妇难为无米之炊:
      - 配置开发环境: build-environment/building.md
      - 基础设置: build-environment/settings.md
      - 一些概念: build-environment/conceptions.md
  - 入门:
      - 啥都没有的模组: basic/mod.md
      - 基础物品: basic/item.md
      - 基础方块: basic/block.md
      - 稍微完善一下: basic/complete.md
      - 本章拓展:
        - 前言: basic/advanced/pre.md
        - 资源专题:
            - Blockstates: basic/advanced/resources/origin.md
            - 模型和材质: basic/advanced/resources/models.md
        - 建议自学内容: basic/advanced/recommend.md
      - 基础概念: basic/conceptions.md
  - 有用的物品:
      - 模组简介: item-basic/introduction.md
      - 新建物品类: item-basic/construct.md
      - 添加功能: item-basic/functions.md
      - 给玩家添加物品: item-basic/add-item.md
      - 本章拓展:
          - 前言: item-basic/advanced/pre.md
          - 建议自学内容: item-basic/advanced/recommend.md
      - 重要概念: item-basic/conceptions.md