site_name: MCG模组教程
theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
repo_url: https://github.com/MineCraftGensoukyo/ModdingTutorial

nav:
  - 折跃门: gateway/gateway.md
  - 前言: index.md
  - 巧妇难为无米之炊:
      - 配置开发环境: build-environment/building.md
      - 基础设置: build-environment/settings.md
      - 一些概念: build-environment/conceptions.md
  - 入门:
      - 啥都没有的模组: basic/mod.md
      - 基础物品: basic/item.md
      - 基础方块: basic/block.md
      - 稍微完善一下: basic/complete.md
      - 本章拓展:
        - 前言: basic/advanced/pre.md
        - 资源专题:
            - Blockstates: basic/advanced/resources/origin.md
            - 模型和材质: basic/advanced/resources/models.md
        - 建议自学内容: basic/advanced/recommend.md
      - 基础概念: basic/conceptions.md
  - 有用的物品:
      - 模组简介: item-basic/introduction.md
      - 新建物品类: item-basic/construct.md
      - 添加功能: item-basic/functions.md
      - 给玩家添加物品: item-basic/add-item.md
      - 本章拓展:
          - 前言: item-basic/advanced/pre.md
          - 建议自学内容: item-basic/advanced/recommend.md
      - 重要概念: item-basic/conceptions.md
  - 有用的方块:
      - 本章内容: block-basic/introduction.md
      - 一些重复的操作: block-basic/construct.md
      - 方块状态: block-basic/blockstates.md
      - 左键？: block-basic/canceled.md
      - 本章拓展:
          - 建议自学内容: block-basic/advanced/recommend.md
  - 一些铺垫:
      - 前言: groundwork/pre.md
      - 网络:
          - 概念描述: groundwork/network/conceptions.md
          - 创建数据包: groundwork/network/packet.md
          - Channel: groundwork/network/channel.md
      - HUD:
          - 概念描述: groundwork/hud/conceptions.md
          - 创建HUD: groundwork/hud/hud.md
      - 本章拓展:
          - 前言: groundwork/advanced/pre.md
  - 自学能力:
      - 前言: self-study/pre.md
      - 搜索引擎（流体制作）:
          - 前言: self-study/engine/pre.md
          - 搜索: self-study/engine/search.md
      - AI:
          - 前言: self-study/ai/pre.md
          - 典型错误:
              - 模型错误: self-study/ai/error/model.md
  - 事件系统:
      - 事件: 6.5-event/event.md
  - 资源生成:
      - 前言: 7-datagen/pre.md
      - 开始: 7-datagen/begin.md
      - 物品: 7-datagen/item.md
      - 方块: 7-datagen/block.md
      - 语言: 7-datagen/language.md
      - 碎碎念: 7-datagen/extra.md
  - 方块实体:
      - 前言: 8-blockentity-basic/pre.md
      - 注册方块实体: 8-blockentity-basic/register.md
      - 基础方块: 8-blockentity-basic/baseentityblock.md
      - 方块实体: 8-blockentity-basic/blockentity.md
      - 方块实体的渲染: 8-blockentity-basic/render.md
      - 容器: 8-blockentity-basic/container.md
      - 示例: 8-blockentity-basic/example.md
  - 实体基础:
      - 前言: 9-base-entity/pre.md
      - 注册: 9-base-entity/register.md
      - 基础: 9-base-entity/base.md
  - 能力:
      - 前言: 10-capability/pre.md
      - 开始使用能力: 10-capability/begin.md
      - 使用预定义能力: 10-capability/handler.md
  - 黑魔法:
      - 前言: magic/pre.md
      - AT: magic/at.md
      - mixin: magic/mixin.md